### PR TITLE
Fix double `MarkdownBlock` EasyMDE initialisation

### LINKED ISSUE #141: double markdown block
I am following the documentation and started a brand new project.
I added a page class with a body such as:
```
    body = StreamField(
        [
            ("heading", blocks.CharBlock(form_classname="title")),
            ("paragraph", blocks.RichTextBlock()),
            ("image", ImageChooserBlock()),
            ("markdown", MarkdownBlock(icon="code")),
        ]
    )
```

image

image

What am I missing ?.  If this is a real bug (and not a code 18), point me in the right direction so I can try to contribute.

Thank you

### PR DESCRIPTION
**Pull request by zerolab**
Fixes #141

@lb- suggested a conditional

```js
if (!element.matches('[data-controller~="easymde"') {
   // Wagtail 6.0, using data attribute (Stimulus), does not require Telepath to instantiate MD Editor
    easymdeAttach(id);
}
```

in the `wagtailmarkdown/js/markdown-textarea-adapter.js` Telepath adapter, but that is really not needed with the new controller

### CODE REVIEW

**Comment by zerolab** [comment]
@lb- would appreciate your input on this

File: src/wagtailmarkdown/static/wagtailmarkdown/js/easymde-controller.js [hunk 1]
```diff
@@ -1,12 +1,11 @@
-// wagtailmarkdown/static/wagtailmarkdown/js/easymde-controller.js
-
 class EasyMDEContainer extends window.StimulusModule.Controller {
-    static values = { autodownload: Boolean };
+    static values = { autodownload: Boolean};
 
     connect() {
-        if (this.autodownloadValue != null) {
+        if (this.hasAutodownloadValue) {
```
Comment (zerolab) [inline src/wagtailmarkdown/static/wagtailmarkdown/js/easymde-controller.js:5]: tl;dr - EasyMDE will try to detect if FA is present if initialized with a null value. Given `static values = { autodownload: Boolean};` a missing value would be false, so we were initialising EasyMDE with "don't download FA"

**Review by softquantum — APPROVED** [review]
tested locally and it fixed the issue in #141

**Review by softquantum — APPROVED** [review]

File: src/wagtailmarkdown/static/wagtailmarkdown/js/easymde-controller.js (hunk 1 above)
Comment (lb-) [reply src/wagtailmarkdown/static/wagtailmarkdown/js/easymde-controller.js:5]: Sorry. Just reading this now. 

The `hasSomeValue` just checks if the value is declared in the DOM so I'm not sure this is what you want. 

```
<textarea data-controller="easymde" ... (No html data attribute for the value )
// this.hasAutodownloadValue - will be false 
<textarea data-controller="easymde" data-easymde-autodownload="false" ...
// this.hasAutodownloadValue - will be true
<textarea data-controller="easymde"  data-easymde-autodownload="true" ...
// this.hasAutodownloadValue - will be true 
```

I think the issue was the confusion of checking against null with a `!=` as this will try to coerce the Boolean into a comparable value. As a general guide it's good to use strict inequality and try to align checks with the type set of the value. 

Or keep the code simpler with returns or a non-comparison approach.

```
easymdeAttach(this.element.id, this.autodownloadValue);
```

`this.autodownloadValue` will always return a Boolean, Stimulus does this for us, so why do any branch logic at all. The default will be `false` if not set in the html.

Comment (lb-) [reply src/wagtailmarkdown/static/wagtailmarkdown/js/easymde-controller.js:5]: https://stimulus.hotwired.dev/reference/values#properties-and-attributes

Comment (zerolab) [reply src/wagtailmarkdown/static/wagtailmarkdown/js/easymde-controller.js:5]: Thank you for additional context, LB.

`this.hasAutodownloadValue` is what I want because we only set the data attribute the setting is present, hence I only want to pass it down when the attribute is set.

https://github.com/Ionaru/easy-markdown-editor?tab=readme-ov-file#configuration

> autoDownloadFontAwesome: If set to true, force downloads Font Awesome (used for icons). If set to false, prevents downloading. Defaults to undefined, which will intelligently check whether Font Awesome has already been included, then download accordingly.

Comment (lb-) [reply src/wagtailmarkdown/static/wagtailmarkdown/js/easymde-controller.js:5]: Ok. No problems.
